package org.hibernate.tool.eclipse.orm.runtime.legacy;

import org.hibernate.tool.eclipse.orm.runtime.spi.IArtifactCollector;
import org.hibernate.tool.eclipse.orm.runtime.spi.ICfg2HbmTool;
import org.hibernate.tool.eclipse.orm.runtime.spi.IClassMetadata;
import org.hibernate.tool.eclipse.orm.runtime.spi.ICollectionMetadata;
import org.hibernate.tool.eclipse.orm.runtime.spi.IColumn;
import org.hibernate.tool.eclipse.orm.runtime.spi.IConfiguration;
import org.hibernate.tool.eclipse.orm.runtime.spi.ICriteria;
import org.hibernate.tool.eclipse.orm.runtime.spi.IEnvironment;
import org.hibernate.tool.eclipse.orm.runtime.spi.IExporter;
import org.hibernate.tool.eclipse.orm.runtime.spi.IForeignKey;
import org.hibernate.tool.eclipse.orm.runtime.spi.IGenericExporter;
import org.hibernate.tool.eclipse.orm.runtime.spi.IHQLCodeAssist;
import org.hibernate.tool.eclipse.orm.runtime.spi.IHQLCompletionProposal;
import org.hibernate.tool.eclipse.orm.runtime.spi.IHQLQueryPlan;
import org.hibernate.tool.eclipse.orm.runtime.spi.IHbm2DDLExporter;
import org.hibernate.tool.eclipse.orm.runtime.spi.IHibernateMappingExporter;
import org.hibernate.tool.eclipse.orm.runtime.spi.IJoin;
import org.hibernate.tool.eclipse.orm.runtime.spi.INamingStrategy;
import org.hibernate.tool.eclipse.orm.runtime.spi.IOverrideRepository;
import org.hibernate.tool.eclipse.orm.runtime.spi.IPersistentClass;
import org.hibernate.tool.eclipse.orm.runtime.spi.IPrimaryKey;
import org.hibernate.tool.eclipse.orm.runtime.spi.IProperty;
import org.hibernate.tool.eclipse.orm.runtime.spi.IQuery;
import org.hibernate.tool.eclipse.orm.runtime.spi.IQueryExporter;
import org.hibernate.tool.eclipse.orm.runtime.spi.IQueryTranslator;
import org.hibernate.tool.eclipse.orm.runtime.spi.IReverseEngineeringSettings;
import org.hibernate.tool.eclipse.orm.runtime.spi.IReverseEngineeringStrategy;
import org.hibernate.tool.eclipse.orm.runtime.spi.ISchemaExport;
import org.hibernate.tool.eclipse.orm.runtime.spi.ISession;
import org.hibernate.tool.eclipse.orm.runtime.spi.ISessionFactory;
import org.hibernate.tool.eclipse.orm.runtime.spi.ITable;
import org.hibernate.tool.eclipse.orm.runtime.spi.ITableFilter;
import org.hibernate.tool.eclipse.orm.runtime.spi.IType;
import org.hibernate.tool.eclipse.orm.runtime.spi.ITypeFactory;
import org.hibernate.tool.eclipse.orm.runtime.spi.IValue;

public interface IFacadeFactory {
	
	ClassLoader getClassLoader();
	IArtifactCollector createArtifactCollector(Object target);
	ICfg2HbmTool createCfg2HbmTool(Object target);
	INamingStrategy createNamingStrategy(Object target);
	IReverseEngineeringSettings createReverseEngineeringSettings(Object target);
	IReverseEngineeringStrategy createReverseEngineeringStrategy(Object target);
	IOverrideRepository createOverrideRepository(Object target);
	ISchemaExport createSchemaExport(Object target);
	IGenericExporter createGenericExporter(Object target);
	IHbm2DDLExporter createHbm2DDLExporter(Object target);
	IQueryExporter createQueryExporter(Object target);
	ITableFilter createTableFilter(Object target);
	IExporter createExporter(Object target);
	IClassMetadata createClassMetadata(Object target);
	ICollectionMetadata createCollectionMetadata(Object target);
	IColumn createColumn(Object target);
	IConfiguration createConfiguration(Object target);
	ICriteria createCriteria(Object target);
	IEnvironment createEnvironment();
	IForeignKey createForeignKey(Object target);
	IHibernateMappingExporter createHibernateMappingExporter(Object target);
	IHQLCodeAssist createHQLCodeAssist(Object target);
	IHQLCompletionProposal createHQLCompletionProposal(Object target);
	IHQLQueryPlan createHQLQueryPlan(Object target);
	IJoin createJoin(Object target);
	IPersistentClass createPersistentClass(Object target);
	IPrimaryKey createPrimaryKey(Object target);
	IProperty createProperty(Object target);
	IQuery createQuery(Object target);
	IQueryTranslator createQueryTranslator(Object target);
	ISessionFactory createSessionFactory(Object target);
	ISession createSession(Object target);
	IPersistentClass createSpecialRootClass(IProperty property);
	ITable createTable(Object target);
	ITypeFactory createTypeFactory();
	IType createType(Object target);
	IValue createValue(Object target);
	
}
