name: Build and Test

on:
  pull_request:
    branches: [main]

env:
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["17"]
      fail-fast: false

    steps:
    - name: Setup Locale
      run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn clean verify -U -fae -DskipITests=true -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -ntp

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.os }}-${{ matrix.java }}-test-reports
        path: |
          **/*target/surefire-reports/
          **/*.log
