name: Publish reports

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  publish:
    name: Publish Test Report
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'cancelled'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "ubuntu-*-test-reports"
          merge-multiple: false

      - name: Publish aggregated tests reports
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/ubuntu-*-test-reports/**/TEST-*.xml'
          commit: ${{ github.event.workflow_run.head_sha }}
